spring:
  application:
    name: store-metrics-monolith

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:ecom_analytics}
    username: ${DB_USER:admin_user}
    password: ${DB_PASSWORD:production_secure_db_password_here}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # For dev purposes, use validate or flyway in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your_email@gmail.com}
    password: ${MAIL_PASSWORD:your_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mvc:
    static-path-pattern: /**

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

# JWT Secret config
jwt:
  secret: <--JWT SECRET-->
  expiration: 86400000 # 24 hours

# WooCommerce
woocommerce:
  site-url: <--site-url-->
  consumer-key: <--consumer-key-->
  consumer-secret: <--consumer-secret-->

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.apache.kafka: WARN
    org.springframework.security: WARN
    org.springframework.web: INFO
    com.storemetrics: INFO

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"